KitapSecKayitSistemiRepo/Models/Warehouse.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KitapSecKayitSistemiRepo.Models
{
    public class Warehouse
    {
        [Key]
        public int WarehouseId { get; set; }
        public string Place { get; set; }       
        public string OfficerName { get; set; }
        public string PhoneNumber { get; set; }
        public int Size { get; set; }

        


    }
}

KitapSecKayitSistemiRepo/Controllers/WarehouseController.cs
using KitapSecKayitSistemiRepo.Models;
using KitapSecKayitSistemiRepo.Repository.Interface;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace KitapSecKayitSistemiRepo.Controllers
{
    public class WarehouseController : Controller
    {
        public readonly IWarehouse repositoryWarehouse;
        public WarehouseController(IWarehouse repositoryWarehouse)
        {
            this.repositoryWarehouse = repositoryWarehouse;
        }

        public async Task<IActionResult> GetWarehouseList()
        {
            var result=await repositoryWarehouse.GetWarehouse();
            return View(result);
        }



        public async Task<IActionResult> AddWarehouse()
        {
            return View();


        }


        [HttpPost]
        public async Task<IActionResult> AddWarehouse(Warehouse warehouse)
        {
            await repositoryWarehouse.AddWarehouse(warehouse);

            if (warehouse.WarehouseId == 0)
            {
                TempData["warehouseError"] = "Ekleme Başarısız";

            }
            else
            {
                TempData["warehouseSuccess"] = "Ekleme Başarılı";
            }

            return RedirectToAction("GetWarehouseList");
        }


        public async Task<IActionResult> Edit(int id)
        {
            Warehouse warehouse = new Warehouse();
            try
            {
                if (id == 0)
                {
                    return BadRequest();
                }
                else
                {

                    warehouse = await repositoryWarehouse.GetWarehouseById(id);
                    if (warehouse.WarehouseId == 0)
                    {
                        return NotFound();
                    }

                }




            }
            catch (System.Exception)
            {

                throw;
            }


            return View(warehouse);



        }

        [HttpPost]
        public async Task<IActionResult> Edit(Warehouse warehouse)
        {

            bool result = await repositoryWarehouse.UpdateWarehouse(warehouse);

            if (warehouse.WarehouseId==0)
            {
                TempData["warehouseError"] = "Güncelleme Başarısız";
            }
            else
            {
                TempData["warehouseSuccess"] = "Güncelleme Başarılı";
            }
            return RedirectToAction("GetWarehouseList");
        }


        public async Task<IActionResult> Delete(int id)
        {
            Warehouse warehouse = new Warehouse();
            try
            {
                if (id == 0)
                {

                    return BadRequest();
                }
                else
                {
                    warehouse = await repositoryWarehouse.GetWarehouseById(id);
                    if (warehouse == null)
                    {
                        return NotFound();
                    }


                }

            }
            catch (Exception)
            {

                throw;
            }
            return View(warehouse);

        }



        [HttpPost]
        public async Task<IActionResult> Delete(Warehouse warehouse)
        {
            bool status = await repositoryWarehouse.DeleteWarehouse(warehouse);
            if (warehouse.WarehouseId == 0)
            {

                TempData["warehouseError"] = "Silme Başarısız";


            }
            else
            {
                TempData["warehouseSuccess"] = "Silme Başarılı";
            }

            return RedirectToAction("GetWarehouseList");
        }


    }
}

KitapSecKayitSistemiRepo/Views/Warehouse/AddWarehouse.cshtml
@model KitapSecKayitSistemiRepo.Models.Warehouse

@{
    ViewData["Title"] = "AddWarehouse";
}

<div class="container">
    <div class="row">
        <div class="col-6 offset-3 border border-4 rounded rounded-3 p-4">
            <h3 class="text-info p-2 m-1 text-center">Add Warehouse</h3>
            <form method="post" asp-action="AddWarehouse">
                <div class="form-check">
                    <label asp-for="Place"></label>
                    <input type="text" asp-for="Place" class="form-control" placeholder="Enter place" />

                </div>

              
                <div class="form-check">
                    <label asp-for="OfficerName"></label>
                    <input type="text" asp-for="OfficerName" class="form-control" placeholder="Enter OfficerName" />
                </div>
                <div class="form-check">
                    <label asp-for="PhoneNumber"></label>
                    <input type="text" asp-for="PhoneNumber" class="form-control" placeholder="Enter PhoneNumber" />
                </div>
                <div class="form-check">
                    <label asp-for="Size"></label>
                    <input type="number" asp-for="Size" class="form-control" placeholder="Enter Size" />
                </div>

            </form>
        </div>
    </div>
</div>

KitapSecKayitSistemiRepo/Views/Warehouse/Delete.cshtml
@model KitapSecKayitSistemiRepo.Models.Warehouse

@{
    ViewData["Title"] = "Delete";
}
<div style="margin-left:500px;">
    <h1>Delete</h1>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Warehouse</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Place)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Place)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.OfficerName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.OfficerName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PhoneNumber)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Size)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Size)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="WarehouseId" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-action="GetWarehouseList">Back to List</a>
        </form>
    </div>
</div>

KitapSecKayitSistemiRepo/Views/Warehouse/Edit.cshtml
@model KitapSecKayitSistemiRepo.Models.Warehouse

@{
    ViewData["Title"] = "Edit";
}

<div class="container">
    <div class="row">
        <div class="col-6 offset-3 border border-4 rounded rounded-3 p-4">
            <h3 class="text-info p-2 m-1 text-center">Update Warehouse</h3>
            <form method="post" asp-action="Edit">
                <div class="form-check">
                    <label asp-for="Place"></label>
                    <input type="text" asp-for="Place" class="form-control" placeholder="Enter Place" />
                    <input type="hidden" asp-for="WarehouseId" />
                    <span class="text-danger" asp-validation-for="Place"></span>
                </div>

               
                <div class="form-check">
                    <label asp-for="OfficerName"></label>
                    <input type="text" asp-for="OfficerName" class="form-control" placeholder="Enter OfficerName" />
                    <span class="text-danger" asp-validation-for="OfficerName"></span>

                </div>
                <div class="form-check">
                    <label asp-for="PhoneNumber"></label>
                    <input type="text" asp-for="PhoneNumber" class="form-control" placeholder="Enter PhoneNumber" />
                    <span class="text-danger" asp-validation-for="PhoneNumber"></span>

                </div>
                <div class="form-check">
                    <label asp-for="Size"></label>
                    <input type="number" asp-for="Size" class="form-control" placeholder="Enter Size" />
                    <span class="text-danger" asp-validation-for="Size"></span>

                </div>
               
                <div>
                    <input type="submit" class="btn btn-sm btn-warning m-2 p-2 float-end" value="Update" />
                </div>

            </form>
        </div>
    </div>
</div>

KitapSecKayitSistemiRepo/Views/Warehouse/GetWarehouseList.cshtml
@model IEnumerable<KitapSecKayitSistemiRepo.Models.Warehouse>

@{
    ViewData["Title"] = "GetWarehouseList";
}



<div class="container">
    <div class="row">
        @if (TempData["warehouseError"] != null)
        {

            <div class="alert alert-danger notification text-center">

                @TempData["warehouseError"]
            </div>

        }

        @if (TempData["warehouseSuccess"] != null)
        {

            @TempData["warehouseSuccess"]


        }

        <div class="col-10 offset-1">

            <div class="float-end">
                <a class="btn btn-sm btn-primary p-1 m-1" asp-action="AddWarehouse" asp-controller="Warehouse">Add Warehouse</a>
            </div>

            <table class="table table-hover table-striped table-bordered ">
                <thead class="text-center table-striped table-bordered">
                    <tr>
                        <th>Warehouse Id</th>
                        <th>Place</th>
                        <th>Officer Name</th>
                        <th>Phone Number</th>
                        <th>Size</th>
                       

                    </tr>

                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr class="text-center">

                            <td>@item.WarehouseId</td>
                            <td>@item.Place</td>
                            <td>@item.OfficerName</td>
                            <td>@item.PhoneNumber</td>
                            <td>@item.Size</td>
                     


                            <td>

                                <a class="btn btn-sm btn-warning m-1" asp-controller="Warehouse" asp-action="Edit" asp-route-id="@item.WarehouseId">Edit</a>
                                <a class="btn btn-sm btn-danger m-1" asp-controller="Warehouse" asp-action="Delete" asp-route-id="@item.WarehouseId">Delete</a>
                            </td>

                        </tr>



                    }


                </tbody>


            </table>

        </div>

    </div>

</div>