KitapSecKayitSistemiRepo/Models/Truck.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KitapSecKayitSistemiRepo.Models
{
    public class Truck
    {
        [Key]
        public int TruckId { get; set; }
        public string TruckDriver { get; set; }
        public string DriverPhone { get; set; }
        public int TruckSize { get; set; }
        public string DrivingLicenceNumber { get; set; }
        public string NumberPlate { get; set; }

        public int WarehouseId { get; set; }
        [ForeignKey("WarehouseId")]
        public virtual Warehouse Warehouses { get; set; }


    }
}

KitapSecKayitSistemiRepo/Controllers/TruckController.cs
using KitapSecKayitSistemiRepo.Data;
using KitapSecKayitSistemiRepo.Models;
using KitapSecKayitSistemiRepo.Repository.Interface;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace KitapSecKayitSistemiRepo.Controllers
{
    public class TruckController : Controller
    {
        public readonly ITruck repositoryTruck;
        public TruckController(ITruck repositoryTruck)
        {
            this.repositoryTruck = repositoryTruck;
        }



        public async Task<IActionResult> GetTruckList()
        {
            var result = await repositoryTruck.GetTruckList();
            return View(result);


        }



        public async Task<IActionResult> AddTruck()
        {
            return View();

        }

        [HttpPost]
        public async Task<IActionResult> AddTruck(Truck truck)
        {
            await repositoryTruck.AddTruck(truck);

            if (truck.TruckId == 0)
            {
                TempData["truckError"] = "Kayıt Başarısız";


            }
            else
            {
                TempData["truckSuccess"] = "Kayıt Başarılı";


            }
            return RedirectToAction("GetTruckList");

        }


        public async Task<IActionResult> Edit(int id)
        {
            Truck truck = new Truck();
            try
            {
                if (id == 0)
                {
                    return BadRequest();
                }
                else
                {
                    truck = await repositoryTruck.GetTruckById(id);

                    if (truck == null)
                    {
                        return NotFound();
                    }


                }
            }
            catch (System.Exception)
            {

                throw;
            }
            return View(truck);

          
        }



        [HttpPost]
        public async Task<IActionResult> Edit(Truck truck)
        {
            if (truck != null)
            {
                bool result = await repositoryTruck.UpdateTruck(truck);
                if (truck.TruckId == 0)
                {
                    TempData["truckError"] = "Güncelleme Başarısız";
                }
                else
                {
                    TempData["truckSuccess"] = "Güncelleme Başarılı";
                }

            }
            return RedirectToAction("GetTruckList");

        }



        public async Task<IActionResult> Delete(int id)
        {
            Truck truck = new Truck();
            try
            {
                if (id == 0)
                {

                    return BadRequest();
                }
                else
                {
                    truck = await repositoryTruck.GetTruckById(id);
                    if (truck == null)
                    {
                        return NotFound();
                    }


                }

            }
            catch (Exception)
            {

                throw;
            }
            return View(truck);

        }



        [HttpPost]
        public async Task<IActionResult> Delete(Truck truck)
        {
            bool status = await repositoryTruck.DeleteTruck(truck);
            if (truck.TruckId == 0)
            {

                TempData["truckError"] = "Silme Başarısız";


            }
            else
            {
                TempData["truckSuccess"] = "Silme Başarılı";
            }

            return RedirectToAction("GetTruckList");
        }


    }
}

KitapSecKayitSistemiRepo/Views/Truck/AddTruck.cshtml
@model KitapSecKayitSistemiRepo.Models.Truck

@{
    ViewData["Title"] = "AddTruck";
}
<div class="container">
    <div class="row">
        <div class="col-6 offset-3 border border-4 rounded rounded-3 p-4">
            <h3 class="text-info p-2 m-1 text-center">Add Truck</h3>
            <form method="post" asp-action="AddTruck">
                <div class="form-check">
                    <label asp-for="TruckDriver"></label>
                    <input type="text" asp-for="TruckDriver" class="form-control" placeholder="Enter TruckDriver" />

                </div>

                <div class="form-check">
                    <label asp-for="DriverPhone"></label>
                    <input type="text" asp-for="DriverPhone" class="form-control" placeholder="Enter DriverPhone" />
                </div>
                <div class="form-check">
                    <label asp-for="TruckSize"></label>
                    <input type="number" asp-for="TruckSize" class="form-control" placeholder="Enter Truck Size" />
                </div>
                <div class="form-check">
                    <label asp-for="DrivingLicenceNumber"></label>
                    <input type="text" asp-for="DrivingLicenceNumber" class="form-control" placeholder="Enter DrivingLicenceNumber" />
                </div>
                <div class="form-check">
                    <label asp-for="NumberPlate"></label>
                    <input type="text" asp-for="NumberPlate" class="form-control" placeholder="Enter Number Plate" />
                </div>
            
                <div class="form-group">
                    <label asp-for="WarehouseId" class="control-label"></label>
                    <input asp-for="WarehouseId" class="form-control" />
                    <span asp-validation-for="WarehouseId" class="text-danger"></span>
                </div>

            </form>
        </div>
    </div>
</div>

KitapSecKayitSistemiRepo/Views/Truck/Delete.cshtml
@model KitapSecKayitSistemiRepo.Models.Truck

@{
    ViewData["Title"] = "Delete";
}
<div style="margin-left:500px;">
<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Truck</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TruckDriver)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TruckDriver)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DriverPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DriverPhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TruckSize)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TruckSize)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DrivingLicenceNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DrivingLicenceNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberPlate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberPlate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Warehouses)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Warehouses.WarehouseId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TruckId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</div>

KitapSecKayitSistemiRepo/Views/Truck/Edit.cshtml
@model KitapSecKayitSistemiRepo.Models.Truck

@{
    ViewData["Title"] = "Edit";
}

<div class="container">
    <div class="row">
        <div class="col-6 offset-3 border border-4 rounded rounded-3 p-4">
            <h3 class="text-info p-2 m-1 text-center">Update Truck</h3>
            <form method="post" asp-action="Edit">
                <div class="form-check">
                    <label asp-for="TruckDriver"></label>
                    <input type="text" asp-for="TruckDriver" class="form-control" placeholder="Enter name" />
                    <input type="hidden" asp-for="TruckId" />
                    <span class="text-danger" asp-validation-for="TruckDriver"></span>
                </div>

           
                <div class="form-check">
                    <label asp-for="DriverPhone"></label>
                    <input type="text" asp-for="DriverPhone" class="form-control" placeholder="Enter DriverPhone" />
                    <span class="text-danger" asp-validation-for="DriverPhone"></span>

                </div>
                <div class="form-check">
                    <label asp-for="TruckSize"></label>
                    <input type="number" asp-for="TruckSize" class="form-control" placeholder="Enter TruckSize" />
                    <span class="text-danger" asp-validation-for="TruckSize"></span>

                </div>
                <div class="form-check">
                    <label asp-for="DrivingLicenceNumber"></label>
                    <input type="text" asp-for="DrivingLicenceNumber" class="form-control" placeholder="Enter DriverPhone" />
                    <span class="text-danger" asp-validation-for="DrivingLicenceNumber"></span>

                </div>
                <div class="form-check">
                    <label asp-for="NumberPlate"></label>
                    <input type="text" asp-for="NumberPlate" class="form-control" placeholder="Enter NumberPlate" />
                    <span class="text-danger" asp-validation-for="NumberPlate"></span>

                </div>
                <div class="form-check">
                    <label asp-for="WarehouseId"></label>
                    <input type="number" asp-for="WarehouseId" class="form-control" placeholder="Enter Warehouse Id" />
                    <span class="text-danger" asp-validation-for="WarehouseId"></span>

                </div>
               
                <div>
                    <input type="submit" class="btn btn-sm btn-warning m-2 p-2 float-end" value="Update" />
                </div>

            </form>
        </div>
    </div>
</div>

KitapSecKayitSistemiRepo/Views/Truck/GetTruckList.cshtml
@model IEnumerable<KitapSecKayitSistemiRepo.Models.Truck>

@{
    ViewData["Title"] = "GetTruckList";
}



<div class="container">
    <div class="row">
        @if (TempData["truckError"] != null)
        {

            <div class="alert alert-danger notification text-center">

                @TempData["truckError"]
            </div>

        }

        @if (TempData["truckSuccess"] != null)
        {

            @TempData["truckSuccess"]


        }

        <div class="col-10 offset-1">

            <div class="float-end">
                <a class="btn btn-sm btn-primary p-1 m-1" asp-action="AddTruck" asp-controller="Truck">Add Truck</a>
            </div>

            <table class="table table-hover table-striped table-bordered ">
                <thead class="text-center table-striped table-bordered">
                    <tr>
                        <th>Truck Id</th>
                        <th>Truck Driver</th>
                        <th>Driver Phone</th>
                        <th>Truck Size</th>
                        <th>Licence Number</th>
                        <th>Number Plate</th>
                        <th>Warehouse Id</th>
                    

                    </tr>

                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr class="text-center">

                            <td>@item.TruckId</td>
                            <td>@item.TruckDriver</td>
                            <td>@item.DriverPhone</td>
                            <td>@item.TruckSize</td>
                            <td>@item.DrivingLicenceNumber</td>
                            <td>@item.NumberPlate</td>
                            <td>@item.WarehouseId</td>


                            <td>

                                <a class="btn btn-sm btn-warning m-1" asp-controller="Truck" asp-action="Edit" asp-route-id="@item.TruckId">Edit</a>
                                <a class="btn btn-sm btn-danger m-1" asp-controller="Truck" asp-action="Delete" asp-route-id="@item.TruckId">Delete</a>
                            </td>

                        </tr>



                    }


                </tbody>


            </table>

        </div>

    </div>

</div>