KitapSecKayitSistemiRepo/Models/Seller.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace KitapSecKayitSistemiRepo.Models
{
    public class Seller
    {
        [Key]
        public int SellerId { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public DateTime FoundationDate { get; set; }
        public string Address { get; set; }


    }
}

KitapSecKayitSistemiRepo/Controllers/SellerController.cs
using KitapSecKayitSistemiRepo.Models;
using KitapSecKayitSistemiRepo.Repository.Interface;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace KitapSecKayitSistemiRepo.Controllers
{
    public class SellerController : Controller
    {
        public readonly ISeller repositorySeller;
        public SellerController(ISeller repositorySeller)
        {
            this.repositorySeller = repositorySeller;
        }


        public async Task<IActionResult> GetSellerList()
        {
            var result = await repositorySeller.GetSellerList();
            return View(result);
        }

        public async Task<IActionResult> AddSeller()
        {
            return View();
        }



        [HttpPost]
        public async Task<IActionResult> AddSeller(Seller seller)
        {

            await repositorySeller.AddSeller(seller);
            if (seller.SellerId == 0)
            {

                TempData["sellerError"] = "Kayıt Başarısız";

            }
            else
            {
                TempData["sellerSuccess"] = "Kayıt Başarılı";


            }
            return RedirectToAction("GetSellerList");

        }

        public async Task<IActionResult> Edit(int id)
        {
            Seller seller = new Seller();

            try
            {
                if (id == 0)
                {  
                    return BadRequest(); 
                }
                 
                else
                {
                    seller=await repositorySeller.GetSellerById(id);
                    if (seller==null)
                    {
                        return NotFound();

                    }

                }
            }
            catch (Exception)
            {

                throw;
            }

            return View(seller);



        }
        [HttpPost]
        public async Task<IActionResult> Edit(Seller seller)
        {
            bool status = await repositorySeller.UpdateSeller(seller);
            if (seller.SellerId==0)
            {
               
                TempData["sellerError"] = "Güncelleme Başarısız";


            }
            else
            {

                TempData["sellerSuccess"] = "Güncelleme Başarılı";
            }
            return RedirectToAction("GetSellerList");
           
        }


        public async Task<IActionResult> Delete(int id)
        {
            Seller seller = new Seller();
            try
            {
                if (id == 0)
                {

                    return BadRequest();
                }
                else
                {
                    seller = await repositorySeller.GetSellerById(id);
                    if (seller == null)
                    {
                        return NotFound();
                    }


                }

            }
            catch (Exception)
            {

                throw;
            }
            return View(seller);

        }



        [HttpPost]
        public async Task<IActionResult> Delete(Seller seller)
        {
            bool status = await repositorySeller.DeleteSeller(seller);
            if (seller.SellerId == 0)
            {

                TempData["sellerError"] = "Silme Başarısız";


            }
            else
            {
                TempData["sellerSuccess"] = "Silme Başarılı";
            }

            return RedirectToAction("GetSellerList");
        }


    }
}

KitapSecKayitSistemiRepo/Views/Seller/AddSeller.cshtml
@model KitapSecKayitSistemiRepo.Models.Seller

@{
    ViewData["Title"] = "AddSeller";
}

<div class="container">
    <div class="row">
        <div class="col-6 offset-3 border border-4 rounded rounded-3 p-4">
            <h3 class="text-info p-2 m-1 text-center">Add Seller</h3>
            <form method="post" asp-action="AddSeller">
                <div class="form-check">
                    <label asp-for="Name"></label>
                    <input type="text" asp-for="Name" class="form-control" placeholder="Enter name" />

                </div>


                <div class="form-check">
                    <label asp-for="LastName"></label>
                    <input type="text" asp-for="LastName" class="form-control" placeholder="Enter Last Name" />
                </div>
                <div class="form-check">
                    <label asp-for="PhoneNumber"></label>
                    <input type="text" asp-for="PhoneNumber" class="form-control" placeholder="Enter Phone Number" />
                </div>
                   <div class="form-check">
                    <label asp-for="FoundationDate"></label>
                    <input type="date" asp-for="FoundationDate" class="form-control" placeholder="Enter Foundation Date" />
                </div>   <div class="form-check">
                    <label asp-for="Address"></label>
                    <input type="text" asp-for="Address" class="form-control" placeholder="Enter Address" />
                    <div>
                        <input type="submit" class="btn btn-sm btn-primary m-2 p-2 float-end" value="Save" />
                    </div>
                </div>


             

            </form>
        </div>
    </div>
</div>

KitapSecKayitSistemiRepo/Views/Seller/Delete.cshtml
@model KitapSecKayitSistemiRepo.Models.Seller

@{
    ViewData["Title"] = "Delete";
}
<div style="margin-left:500px;">
    <h1>Delete</h1>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Seller</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.LastName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.LastName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PhoneNumber)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.FoundationDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.FoundationDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Address)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Address)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="SellerId" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-action="GetSellerList">Back to List</a>
        </form>
    </div>
</div>

KitapSecKayitSistemiRepo/Views/Seller/Edit.cshtml
@model KitapSecKayitSistemiRepo.Models.Seller

@{
    ViewData["Title"] = "Edit";
}

<div class="container">
    <div class="row">
        <div class="col-6 offset-3 border border-4 rounded rounded-3 p-4">
            <h3 class="text-info p-2 m-1 text-center">Update Seller </h3>
            <form method="post" asp-action="Edit">
                <div class="form-check">
                    <label asp-for="Name"></label>
                    <input type="text" asp-for="Name" class="form-control" placeholder="Enter name" />
                    <input type="hidden" asp-for="SellerId" />
                    <span class="text-danger" asp-validation-for="Name"></span>
                </div>

              
                <div class="form-check">
                    <label asp-for="LastName"></label>
                    <input type="text" asp-for="LastName" class="form-control" placeholder="Enter LastName" />
                    <span class="text-danger" asp-validation-for="LastName"></span>

                </div>
                <div class="form-check">
                    <label asp-for="PhoneNumber"></label>
                    <input type="text" asp-for="PhoneNumber" class="form-control" placeholder="Enter PhoneNumber" />
                    <span class="text-danger" asp-validation-for="PhoneNumber"></span>

                </div>
                <div class="form-check">
                    <label asp-for="FoundationDate"></label>
                    <input type="date" asp-for="FoundationDate" class="form-control" placeholder="Enter FoundationDate" />
                    <span class="text-danger" asp-validation-for="FoundationDate"></span>

                </div>

                <div>
                    <input type="submit" class="btn btn-sm btn-warning m-2 p-2 float-end" value="Update" />
                </div>

            </form>
        </div>
    </div>
</div>

KitapSecKayitSistemiRepo/Views/Seller/GetSellerList.cshtml
@model IEnumerable<KitapSecKayitSistemiRepo.Models.Seller>

@{
    ViewData["Title"] = "GetSellerList";
}



<div class="container">
    <div class="row">
        @if (TempData["sellerError"] != null)
        {

            <div class="alert alert-danger notification text-center">

                @TempData["sellerError"]
            </div>

        }

        @if (TempData["sellerSuccess"] != null)
        {

            @TempData["sellerSuccess"]


        }

        <div class="col-10 offset-1">

            <div class="float-end">
                <a class="btn btn-sm btn-primary p-1 m-1" asp-action="AddSeller" asp-controller="Seller">Add Seller</a>
            </div>

            <table class="table table-hover table-striped table-bordered ">
                <thead class="text-center table-striped table-bordered">
                    <tr>
                        <th>Seller Id</th>
                        <th>Name</th>
                        <th>Lastname</th>
                        <th>Phone Number</th>
                        <th>Foundation Date</th>
                        <th>Address</th>
                       
                    </tr>

                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr class="text-center">

                            <td>@item.SellerId</td>
                            <td>@item.Name</td>
                            <td>@item.LastName</td>                        
                            <td>@item.PhoneNumber</td>
                            <td>@item.FoundationDate</td>
                            <td>@item.Address</td>
                         

                            <td>

                                <a class="btn btn-sm btn-warning m-1" asp-controller="Seller" asp-action="Edit" asp-route-id="@item.SellerId">Edit</a>
                                <a class="btn btn-sm btn-danger m-1" asp-controller="Seller" asp-action="Delete" asp-route-id="@item.SellerId">Delete</a>
                            </td>

                        </tr>



                    }


                </tbody>


            </table>

        </div>

    </div>

</div>